"""user

Revision ID: 6ef1470e0365
Revises: 917acaf7b711
Create Date: 2025-12-30 09:46:59.579941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ef1470e0365'
down_revision: Union[str, Sequence[str], None] = '917acaf7b711'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('keycloak_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_keycloak_id'), 'users', ['keycloak_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_keycloak_id'), table_name='users')
    op.drop_column('users', 'keycloak_id')
    # ### end Alembic commands ###
