"""chat_table

Revision ID: 917acaf7b711
Revises: 4c115365b9a6
Create Date: 2025-12-28 15:45:40.068502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '917acaf7b711'
down_revision: Union[str, Sequence[str], None] = '4c115365b9a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chats_response_key'), 'chats', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('chats_response_key'), 'chats', ['response'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
