"""chunk_table

Revision ID: e06f5faf2dd0
Revises: e159d635989c
Create Date: 2026-01-17 18:14:25.576973

"""
from typing import Sequence, Union

from alembic import op
import pgvector
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e06f5faf2dd0'
down_revision: Union[str, Sequence[str], None] = 'e159d635989c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.add_column('chunks', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('chunks', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False))
    op.alter_column('chunks', 'document_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('chunks', 'chunk_index',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('chunks', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_index(op.f('ix_chunks_document_id'), 'chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_chunks_user_id'), 'chunks', ['user_id'], unique=False)
    op.drop_constraint(op.f('chunks_document_id_fkey'), 'chunks', type_='foreignkey')
    op.create_foreign_key(None, 'chunks', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'chunks', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.execute("DROP EXTENSION IF EXISTS vector")

    op.drop_constraint(None, 'chunks', type_='foreignkey')
    op.drop_constraint(None, 'chunks', type_='foreignkey')
    op.create_foreign_key(op.f('chunks_document_id_fkey'), 'chunks', 'documents', ['document_id'], ['id'])
    op.drop_index(op.f('ix_chunks_user_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_document_id'), table_name='chunks')
    op.alter_column('chunks', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('chunks', 'chunk_index',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('chunks', 'document_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('chunks', 'embedding')
    op.drop_column('chunks', 'user_id')
    # ### end Alembic commands ###
